In [1]:
import numpy as np
import matplotlib.pyplot as plt
import sys

sys.path.insert(0, '/scratch/fivanovic/X-SH/T6-PDI/production_runs/analysis_scripts')
import xsh_analysis_functions as XSA
import file_parsers

sys.path.insert(0 , '/scratch/fivanovic/Work/X-SH/eigenstate_plotting')
import XSH_eigenstates_Filip as XSF

In [11]:
vecs = XSF.build_lattice(3,1,5)
molecule_indices = [index for index in range(len(vecs))]
nearest_neighbours = XSF.build_connectivity(vecs, 5)

CT_states = XSF.define_CT_states_single_phase(molecule_indices)
XT_states = XSF.define_XT_states(molecule_indices)

H_CT = XSF.build_CT_block(CT_states, vecs, nearest_neighbours, 0, 50, 50, 0)
H_XT = XSF.build_XT_block(XT_states, nearest_neighbours, 0, 50)
H_XT_CT = XSF.build_XT_CT_block(XT_states, CT_states, nearest_neighbours, coupling=None, XT_hole_coupling=50, XT_electron_coupling=25)

H = XSF.build_full_Hamiltonian(H_CT, H_XT, H_XT_CT)
print(H)

[[ 0. 50.  0.  0.  0.  0. 25. 50.  0.]
 [50.  0.  0. 50.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. 50.  0. 50. 25.  0.]
 [ 0. 50.  0.  0.  0.  0.  0. 25. 50.]
 [ 0.  0. 50.  0.  0. 50.  0.  0.  0.]
 [ 0.  0.  0.  0. 50.  0.  0. 50. 25.]
 [25.  0. 50.  0.  0.  0.  0. 50.  0.]
 [50.  0. 25. 25.  0. 50. 50.  0. 50.]
 [ 0.  0.  0. 50.  0. 25.  0. 50.  0.]]


In [3]:
sim_H = file_parsers.xyz_parser('pseudoH_3PDI_noXTCT_FRZcoup.xyz', 3)
sim_H = XSA.build_sim_H(sim_H, 9)*27211

for j in range(len(sim_H)):

    sim_H[j,j] = 0

print(np.max(H - sim_H))

0.0025085999999987507
